version: '3.1'

services:
  platform-php-apache:
    image: platform-php-apache
    container_name: platform-php-apache
    build:
      context: .
      dockerfile: Dockerfile
      args:
        project_path: /var/www/html/
        uid: 1000
        user: platform_user
    restart: unless-stopped
    ports:
      - 1000:80
    volumes:
      - ./:/var/www/html
    depends_on:
      - platform-db
      - platform-redis
    links:
      - platform-db
      - platform-redis
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  platform-worker:
    image: platform-php-apache
    container_name: platform-worker
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www/html
    command: 'php ./artisan queue:work --sleep=3 --tries=3'
    depends_on:
      - platform-db
      - platform-redis
    links:
      - platform-db
      - platform-redis
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  platform-horizon:
    image: platform-php-apache
    container_name: platform-apache
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www/html:cached
    command: 'php ./artisan horizon'
    depends_on:
      - platform-db
      - platform-redis
    links:
      - platform-db
      - platform-redis
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  platform-redis:
    image: redis:5-alpine
    restart: unless-stopped
    container_name: platform-redis
    ports:
     - 6379:6379/tcp
    volumes:
      - ./redis.conf:/etc/redis.conf:ro
      - redisData:/data:cached
    command: redis-server /etc/redis.conf
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  platform-db:
    image: mariadb:10.3
    restart: unless-stopped
    container_name: platform-db
    volumes:
      - ./mariadb.cnf:/etc/mysql/my.cnf:ro
      - dbData:/var/lib/mysql:cached
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: omr
      MYSQL_USER: omr
      MYSQL_PASSWORD: omr
      MYSQL_ROOT_PASSWORD: omr
    command: mysqld --sql_mode=""
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  platform-adminer:
    image: adminer
    container_name: platform-adminer
    ports:
      - 8080:8080
    depends_on:
      - platform-db

volumes:
  dbData:
  redisData:
